#### Consider the below code to answer further questions:

In [39]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)


#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [40]:
print(f"Data type of list_ : {type(list_)}")
print(f"Data type of array_list : {type(array_list)}")

Data type of list_ : <class 'list'>
Data type of array_list : <class 'numpy.ndarray'>


___

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [41]:
# Data type of each element of list_
print("'list_' elements and their data type:")
for element in list_:
    print(f"{element} : {type(element)}")

'list_' elements and their data type:
1 : <class 'str'>
2 : <class 'str'>
3 : <class 'str'>
4 : <class 'str'>
5 : <class 'str'>


In [42]:
# Data type of each element of array_list
print("'array_list' elements and their data type:")
for i in range(len(array_list)):
    print(f"{array_list[i]} : {type(array_list[i])}")

'array_list' elements and their data type:
1 : <class 'numpy.str_'>
2 : <class 'numpy.str_'>
3 : <class 'numpy.str_'>
4 : <class 'numpy.str_'>
5 : <class 'numpy.str_'>


___

#### Q3. Considering the following changes in the variable, array_list:

In [43]:
array_list = np.array(object = list_, dtype = int)

#### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

There will be difference in the elements present in **array_list**. In the original code, the data type of each elements in array_list was `'numpy.str_'` and now it would be changed to `'numpy.int64'`

In [44]:
# Data type of each element of list_
print("'list_' elements and their data type:")
for element in list_:
    print(f"{element} : {type(element)}")

# Data type of each element of array_list
print("'array_list' elements and their data type:")
for i in range(len(array_list)):
    print(f"{array_list[i]} : {type(array_list[i])}")


'list_' elements and their data type:
1 : <class 'str'>
2 : <class 'str'>
3 : <class 'str'>
4 : <class 'str'>
5 : <class 'str'>
'array_list' elements and their data type:
1 : <class 'numpy.int64'>
2 : <class 'numpy.int64'>
3 : <class 'numpy.int64'>
4 : <class 'numpy.int64'>
5 : <class 'numpy.int64'>


___

#### Consider the below code to answer further questions:

In [45]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:
* (i) shape
* (ii) size

In [46]:
# shape gives us the shape of the array in number of rows and columns
rows, cols = num_array.shape
print(f"Shape of 'num_array' is : {rows} rows X {cols} columns")

# size gives us the number of elements in the array. It's usually the product of numbers in shape
arr_size = num_array.size
print(f"Shape of 'num_array' is : {arr_size}")

Shape of 'num_array' is : 2 rows X 3 columns
Shape of 'num_array' is : 6


___

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [47]:
# A simple way to create numpy array of 3*3 caontaining only zeroes would be to use NumPy zeros method and specify the shape.

zeros_array = np.zeros((3,3))
print(f"A numpy array of 3*3 caontaining only zeroes:\n{zeros_array}")

# We can also create this passing a list of same size.
list_ = [[0,0,0],[0,0,0],[0,0,0]]
zeros_arr2 = np.array(list_)
print(f"Another numpy array of 3*3 caontaining only zeroes:\n{zeros_arr2}")


A numpy array of 3*3 caontaining only zeroes:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Another numpy array of 3*3 caontaining only zeroes:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


___

#### Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [48]:
# To create an identity matrix we can use NumPy function eye.
eye_matrix = np.eye(5)
print(eye_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


___