In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
print(arr.shape)

(6,)


In [7]:
nested_list = [[1,2,3], [3,4,5], [5,6,7]]
arr2 = np.asarray(nested_list)

In [10]:
arr2.ndim

2

In [11]:
type(arr2)

numpy.ndarray

In [12]:
mat1 = np.matrix(nested_list)

In [13]:
mat1

matrix([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [14]:
type(arr2) == type(mat1)

False

In [17]:
arr2 = np.fromfunction(lambda i, j: i**j, (5,5))

In [18]:
arr2

array([[  1.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   2.,   4.,   8.,  16.],
       [  1.,   3.,   9.,  27.,  81.],
       [  1.,   4.,  16.,  64., 256.]])

In [19]:
my_list = ['A', 'B', 'C', 'D']
np.array(my_list)

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [20]:
list(range(1,5))

[1, 2, 3, 4]

In [21]:
# NumPy arange function can prduce list of floating point numbers as well
np.arange(1,5)

array([1, 2, 3, 4])

In [23]:
np.arange(0.1, 0.8, 0.05)

array([0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 ,
       0.65, 0.7 , 0.75])

In [29]:
# NumPy linespae(a,b, n) will divide the line between a,b by n equal parts and creates an array

np.linspace(1,5,17)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [31]:
np.logspace(1,5,17, base=2)

array([ 2.        ,  2.37841423,  2.82842712,  3.36358566,  4.        ,
        4.75682846,  5.65685425,  6.72717132,  8.        ,  9.51365692,
       11.3137085 , 13.45434264, 16.        , 19.02731384, 22.627417  ,
       26.90868529, 32.        ])

In [36]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
empty_arr = np.empty((3,4))
empty_arr[0]

array([1.        , 1.36363636, 1.72727273, 2.09090909])

In [43]:
np.random.rand(3,4)

array([[0.73901135, 0.72323988, 0.40766462, 0.78169498],
       [0.08297668, 0.63569521, 0.83705207, 0.64302289],
       [0.01222929, 0.74036659, 0.15230725, 0.7770898 ]])

In [48]:
a1 = np.random.rand(5)
a2 = np.random.randn(5)

In [50]:
a2.mean()

0.32994153665113113

In [52]:
np.random.randint(1,10, 10)

array([8, 3, 8, 8, 8, 8, 3, 7, 6, 5])

In [53]:
np.random.randint(1,10,(3,4))

array([[8, 2, 9, 3],
       [3, 7, 2, 9],
       [6, 6, 2, 1]])

In [54]:
arr1 = np.random.randint(1,100, (6, 4))

In [55]:
arr1

array([[40, 79, 80, 51],
       [22, 20, 83, 75],
       [32, 51, 39, 65],
       [78, 99, 60, 12],
       [60, 76,  1,  2],
       [83, 91, 16, 15]])

In [56]:
arr1.reshape(8,3)

array([[40, 79, 80],
       [51, 22, 20],
       [83, 75, 32],
       [51, 39, 65],
       [78, 99, 60],
       [12, 60, 76],
       [ 1,  2, 83],
       [91, 16, 15]])

In [60]:
arr1.reshape(4,-1)

array([[40, 79, 80, 51, 22, 20],
       [83, 75, 32, 51, 39, 65],
       [78, 99, 60, 12, 60, 76],
       [ 1,  2, 83, 91, 16, 15]])

In [61]:
arr1

array([[40, 79, 80, 51],
       [22, 20, 83, 75],
       [32, 51, 39, 65],
       [78, 99, 60, 12],
       [60, 76,  1,  2],
       [83, 91, 16, 15]])

In [62]:
arr1[0]

array([40, 79, 80, 51])

In [66]:
arr1[0, [0,2]] 

array([40, 80])

In [67]:
arr1[0, 0:2]

array([40, 79])

In [68]:
arr1[1:5, [1,2]]

array([[20, 83],
       [51, 39],
       [99, 60],
       [76,  1]])

In [69]:
arr1

array([[40, 79, 80, 51],
       [22, 20, 83, 75],
       [32, 51, 39, 65],
       [78, 99, 60, 12],
       [60, 76,  1,  2],
       [83, 91, 16, 15]])

In [70]:
arr1 > 50

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [False,  True, False,  True],
       [ True,  True,  True, False],
       [ True,  True, False, False],
       [ True,  True, False, False]])

In [71]:
arr1[arr1>50]

array([79, 80, 51, 83, 75, 51, 65, 78, 99, 60, 60, 76, 83, 91])

In [105]:
za = np.zeros((4,3))
oa = np.ones((4,3))
ra1 = np.random.randint(1,5, (4,1))

In [82]:
za = np.zeros((4,6))
oa = np.ones((4,6))
ra1 = np.random.randint(1,5, (4,2))

In [83]:
za

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [84]:
oa

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [85]:
ra1

array([[4, 3],
       [2, 1],
       [4, 2],
       [1, 4]])

In [88]:
oa + ra1[0:4,[0]]

array([[5., 5., 5., 5., 5., 5.],
       [3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5.],
       [2., 2., 2., 2., 2., 2.]])

In [90]:
ra2 = np.random.randint(1,4, (2,3))
ra3 = np.random.randint(1,4, (2,3))

In [95]:
print(f"{ra2} \n {ra3}")

[[3 3 3]
 [2 2 3]] 
 [[3 2 2]
 [3 1 1]]


In [96]:
ra2 + ra3

array([[6, 5, 5],
       [5, 3, 4]])

In [97]:
ra2 - ra3

array([[ 0,  1,  1],
       [-1,  1,  2]])

In [98]:
ra2/ra3

array([[1.        , 1.5       , 1.5       ],
       [0.66666667, 2.        , 3.        ]])

In [99]:
ra2 * ra3

array([[9, 6, 6],
       [6, 2, 3]])

In [100]:
ra2 @ ra3

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [101]:
ra3.T

array([[3, 3],
       [2, 1],
       [2, 1]])

In [102]:
ra2@ra3.T

array([[21, 15],
       [16, 11]])

In [106]:
oa + 9

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [111]:
np.log10(100)

2.0

In [113]:
arr = np.random.randint(1,4,(3,4))

In [114]:
arr.flatten()

array([3, 1, 2, 3, 1, 3, 2, 2, 1, 3, 2, 3])

In [115]:
arr

array([[3, 1, 2, 3],
       [1, 3, 2, 2],
       [1, 3, 2, 3]])

In [116]:
np.diag(arr)

array([3, 3, 2])

In [124]:
np.diag(np.array(np.array([[1,2,3],[2,3,4]])))

array([1, 3])

In [123]:
np.array([[1,2,3],[2,3,4]])

array([[1, 2, 3],
       [2, 3, 4]])

In [125]:
arr2 = np.array([[1,2,3],[2,3,4]])

In [126]:
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [129]:
np.expand_dims(arr2, axis=0).shape

(1, 2, 3)

In [130]:
arr3 = np.expand_dims(arr2, axis=1)

In [131]:
arr3

array([[[1, 2, 3]],

       [[2, 3, 4]]])

In [132]:
np.squeeze(arr3)

array([[1, 2, 3],
       [2, 3, 4]])

In [133]:
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [134]:
np.roll(arr2, 2)

array([[3, 4, 1],
       [2, 3, 2]])

In [1]:
# Sort, Serach and Count

In [3]:
import numpy as np

In [4]:
arr1 = np.random.randint(1, 10, (4,4))

In [6]:
arr1 = np.random.randint(1,10, 9)
arr1

array([5, 7, 7, 2, 4, 8, 5, 2, 2])

In [7]:
np.sort(arr1, )

array([2, 2, 2, 4, 5, 5, 7, 7, 8])

In [8]:
arr2 = np.random.randint(1,20, (3,4))

In [9]:
arr2

array([[ 4, 13, 15, 13],
       [13, 14, 12, 19],
       [16, 16,  7, 16]])

In [10]:
np.sort(arr2)

array([[ 4, 13, 13, 15],
       [12, 13, 14, 19],
       [ 7, 16, 16, 16]])

In [12]:
np.sort(arr2, axis=0)

array([[ 4, 13,  7, 13],
       [13, 14, 12, 16],
       [16, 16, 15, 19]])

In [14]:
np.searchsorted(arr1, 7)

9

In [15]:
arr1

array([5, 7, 7, 2, 4, 8, 5, 2, 2])

In [16]:
np.where(arr1 > arr1.mean())

(array([0, 1, 2, 5, 6]),)

In [17]:
arr1.mean()

4.666666666666667

In [19]:
np.extract(arr1 > arr1.mean(), arr1)

array([5, 7, 7, 8, 5])

In [20]:
arr1[arr1 < 5]

array([2, 4, 2, 2])

In [21]:
arr1[arr1 < 5] = 0

In [22]:
arr1

array([5, 7, 7, 0, 0, 8, 5, 0, 0])

In [23]:
for i in np.nditer(arr1):
    print(i)

5
7
7
0
0
8
5
0
0


In [24]:
for i in np.nditer(arr1):
    if i < 7:
        i = 0

In [25]:
arr1

array([5, 7, 7, 0, 0, 8, 5, 0, 0])

In [26]:
arr2

array([[ 4, 13, 15, 13],
       [13, 14, 12, 19],
       [16, 16,  7, 16]])

In [27]:
arr2[0]

array([ 4, 13, 15, 13])

In [28]:
arr2[1]

array([13, 14, 12, 19])

In [29]:
arr2

array([[ 4, 13, 15, 13],
       [13, 14, 12, 19],
       [16, 16,  7, 16]])

In [30]:
np.unique(arr2)

array([ 4,  7, 12, 13, 14, 15, 16, 19])

In [37]:
arr1 = np.random.randint(0,2,5)
arr2 = np.random.randint(0,2, 5)

In [38]:
arr1

array([1, 1, 1, 0, 0])

In [39]:
arr2

array([1, 0, 0, 0, 1])

In [44]:
np.concatenate(arr2)

ValueError: zero-dimensional arrays cannot be concatenated

In [45]:
arr1 = np.random.randint(0,4, [2,3])
arr2 = np.random.randint(0,4, [2,3])
arr3 = np.random.randint(0,4, [2,3])
arr4 = np.random.randint(0,4, [3,2])

In [46]:
np.concatenate((arr1, arr2))

array([[3, 0, 1],
       [3, 2, 0],
       [2, 3, 1],
       [0, 0, 2]])

In [47]:
np.concatenate((arr1, arr2), axis=1)

array([[3, 0, 1, 2, 3, 1],
       [3, 2, 0, 0, 0, 2]])

In [49]:
np.concatenate((arr3, arr4), axis=None)

array([3, 1, 0, 2, 2, 2, 1, 0, 3, 1, 0, 1])

In [50]:
arr1

array([[3, 0, 1],
       [3, 2, 0]])

In [51]:
np.flip(arr1)

array([[0, 2, 3],
       [1, 0, 3]])

In [52]:
arr3

array([[3, 1, 0],
       [2, 2, 2]])

In [53]:
arr4

array([[1, 0],
       [3, 1],
       [0, 1]])

In [54]:
np.flip(arr4)

array([[1, 0],
       [1, 3],
       [0, 1]])

In [55]:
np.argsort(arr3)

array([[2, 1, 0],
       [0, 1, 2]])

In [56]:
arr3

array([[3, 1, 0],
       [2, 2, 2]])

In [59]:
np.count_nonzero(arr3)

5

In [60]:
arr3

array([[3, 1, 0],
       [2, 2, 2]])

In [5]:
import numpy as np

# Define the desired mean
desired_mean = 70

# Specify the number of data points in each list
num_data_points = 20

# Generate data for the general population using a normal distribution
mean_a = desired_mean
std_dev_a = 30  # You can adjust the standard deviation based on the spread you want
weights_a = np.random.normal(mean_a, std_dev_a, num_data_points)
weights_a

array([ 72.04568949,  40.48501018,  52.93262638,  53.81632993,
         3.05120739,  53.16349342,  79.82847859,  68.83568236,
        44.56511539,  47.93112863,  76.18000151, 110.70610413,
       111.46893254,  73.70605556,  27.52056737,  39.30629026,
        32.67365769,  28.12974702,  37.00589682, -11.17757457])

In [8]:
import numpy as np

# Randomly generate weights for the general population (from 2 months to 80 years)
weights_a = np.random.uniform(5, 100, 20)

# Randomly generate weights for professional football players
# Let's assume football players generally have higher weights
weights_b = np.random.uniform(70, 120, 20)

# Calculate the mean of both lists
mean_a = np.mean(weights_a)
mean_b = np.mean(weights_b)

# Adjust the weights of the second list to match the mean of the first list
weights_b_adjusted = weights_b - (mean_b - mean_a)

# Print the means of both lists
print("Mean of List a:", mean_a)
print("Mean of List b:", np.mean(weights_b_adjusted))


weights_b

Mean of List a: 59.83746296560554
Mean of List b: 59.837462965605525


array([105.40586186, 112.39388716,  97.03314622,  78.64609657,
        71.56121283,  70.30154176, 109.76886283,  95.74980282,
       100.09746473,  71.97700363, 119.45911526,  82.00373162,
       102.71139848, 107.47583371,  97.01786085,  97.37228837,
       117.02655749,  92.47738141, 109.13427581,  85.5216358 ])

In [22]:
plane_a = np.array([30, 50, 10, 80, 90, 45, 60, 100, 90, 80, 40, 15, 55, 50, 75, 80, 60, 40, 95, 90])
plane_a.mean() # 61.75
plane_a.sum() # 1235
plane_a.std() #26.042033330752037

plane_b = np.random.normal(61.75, 8, 20)
plane_b.astype(int)

array([65, 56, 74, 65, 60, 64, 75, 54, 61, 68, 61, 66, 66, 63, 56, 70, 58,
       43, 56, 61])

In [23]:
plane_a = np.array([30, 50, 10, 80, 90, 45, 60, 100, 90, 80, 40, 15, 55, 50, 75, 80, 60, 40, 95, 90])
plane_b = np.array([65, 56, 74, 65, 60, 64, 75, 54, 61, 68, 61, 66, 66, 63, 56, 70, 58, 43, 56, 61])

In [24]:
plane_a.sum()

1235

In [25]:
plane_b.sum()

1242

In [26]:
plane_b.mean()

62.1

In [28]:
plane_a.std()

26.042033330752037

In [29]:
plane_b.std()

7.154718722633337

In [30]:
plane_a.var()

678.1875

In [31]:
plane_b.var()

51.190000000000005

In [45]:
a = [72, 78, 84, 85, 88, 92, 94, 94, 96, 98, 100, 150]
sum(a)/len(a)

94.25

In [38]:
sum(a)

981

In [47]:
import pandas as pd
a = [72, 78, 84, 85, 88, 92, 94, 94, 96, 98, 100]
s = pd.Series(a)
s.std()

8.727178029789261

In [48]:
a = [72, 78, 84, 85, 88, 92, 94, 94, 96, 98, 100, 150]
s = pd.Series(a)
s.std()

19.428774349589652